import assert from "node:assert/strict";
import test from "node:test";
import { getPlan,isPlanKey,pricingPlans,pricingSupplement,PRICING_CATALOG_VERSION,RECOMMENDED_PLAN_KEY } from "./pricing-catalog";
test("versioned pricing catalog retains approved commercial values",()=>{assert.equal(PRICING_CATALOG_VERSION,"2026-07-31");assert.deepEqual(pricingPlans.map(plan=>[plan.key,plan.monthly.amount,plan.setup.amount]),[["starter",200,300],["growth",450,750],["custom",900,1500]]);assert.equal(pricingPlans.find(plan=>plan.recommended)?.key,RECOMMENDED_PLAN_KEY)});
test("pricing support copy is complete in both locales",()=>{for(const locale of ["en","vi"] as const){const copy=pricingSupplement[locale];assert.ok(copy.comparison.title);assert.equal(copy.usage.items.length,3);assert.ok(copy.usage.items.every(item=>item.title&&item.body));assert.ok(copy.faq.items.length>=4);assert.ok(copy.faq.items.every(item=>item.question&&item.answer))}});
test("Starter includes English voice and Tianna AI Calendar without claiming launch-time activation",()=>{const starter=getPlan("starter");const en=starter.features.en.join(" ");assert.match(en,/English call handling/i);assert.match(en,/Tianna AI Calendar included/i);assert.match(en,/booking, rescheduling and cancellation after calendar setup is completed/i);assert.doesNotMatch(en,/Vietnamese|bilingual/i);assert.match(starter.disclaimer.en,/begin in request-only mode/i);assert.match(starter.disclaimer.en,/reviewed and activated/i)});
test("Growth inherits Starter and describes Square setup in customer language",()=>{const growth=getPlan("growth");const en=growth.features.en.join(" ");assert.match(en,/Everything in Starter/i);assert.match(en,/Square Appointments integration/i);assert.match(en,/connection and booking setup are completed/i);assert.doesNotMatch(en,/scheduling workflow|operation capability|external-provider/i);assert.match(growth.disclaimer.en,/does not activate Square Appointments by itself/i)});
test("initial setup is explicitly a separate paid-once onboarding fee",()=>{for(const locale of ["en","vi"] as const){const copy=pricingSupplement[locale];assert.match(copy.comparison.setup,locale==="en"?/paid once/i:/trả một lần/i);assert.match(copy.usage.items[2].body,locale==="en"?/salon profile.*Tianna AI Calendar.*paid once/i:/hồ sơ salon.*Tianna AI Calendar.*trả một lần/i)}});
test("plan keys are stable and invalid values fail closed",()=>{for(const key of ["starter","growth","custom"]){assert.equal(isPlanKey(key),true);assert.equal(getPlan(key as "starter"|"growth"|"custom").key,key)}assert.equal(isPlanKey("enterprise"),false);assert.throws(()=>getPlan("enterprise" as "starter"))});
