"use client";

import { AlertTriangle, ChevronLeft, ChevronRight, ClipboardList, RefreshCcw, Search } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { listRegistrationRequests,type RegistrationListResponse,type RegistrationStatus } from "@/lib/api/tenant-registration";
import { registrationQueueContactLine } from "./tenant-registration-contract";

const statuses:RegistrationStatus[]=["new","in_review","qualified","setup_in_progress","converted","declined","spam"];
const limit=25;

export function TenantRegistrationQueue(){
  const [result,setResult]=useState<RegistrationListResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [offset,setOffset]=useState(0);
  const [draft,setDraft]=useState({query:"",status:"",assigned_to:"",created_from:"",created_to:""});const [filters,setFilters]=useState(draft);const sequence=useRef(0);
  async function load(nextOffset=offset){const request=++sequence.current;const controller=new AbortController();setLoading(true);setError("");try{const data=await listRegistrationRequests({...filters,limit,offset:nextOffset},controller.signal);if(request===sequence.current){setResult(data);setOffset(nextOffset)}}catch(failure){if(request===sequence.current&&!(failure instanceof DOMException&&failure.name==="AbortError"))setError(failure instanceof Error?failure.message:"Could not load registration requests.")}finally{if(request===sequence.current)setLoading(false)}return()=>controller.abort()}
  useEffect(()=>{void load(0)},[filters]);
  function apply(event:FormEvent){event.preventDefault();setFilters({...draft});setOffset(0)}
  const empty=!loading&&!error&&result?.requests.length===0;
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-ink">Registration requests</h1><p className="mt-1 text-sm text-muted">Review pre-tenant salon intake. Intake text never configures providers or scheduling authority.</p></div><Button type="button" variant="secondary" onClick={()=>void load()} disabled={loading}><RefreshCcw className="h-4 w-4"/>Refresh</Button></div>
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{statuses.map(status=><button type="button" key={status} onClick={()=>{setDraft(current=>({...current,status}));setFilters(current=>({...current,status}));setOffset(0)}} className="rounded-lg border border-line bg-white p-3 text-left shadow-soft transition hover:border-teal-300"><div className="text-xs font-semibold uppercase tracking-wide text-muted">{status.replaceAll("_"," ")}</div><div className="mt-1 text-2xl font-bold text-ink">{result?.counts[status]??0}</div></button>)}</div>
    <Card><form className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_180px_170px_160px_160px_auto] lg:items-end" onSubmit={apply}><label><span className="text-sm font-semibold">Search</span><div className="mt-2 flex h-10 items-center gap-2 rounded-md border border-line px-3"><Search className="h-4 w-4 text-muted"/><input className="min-w-0 flex-1 outline-none" value={draft.query} onChange={e=>setDraft({...draft,query:e.target.value})} placeholder="Reference, salon, contact"/></div></label><Filter label="Status"><select className="field mt-2" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="">All</option>{statuses.map(status=><option key={status} value={status}>{status.replaceAll("_"," ")}</option>)}</select></Filter><Filter label="Assignee"><select className="field mt-2" value={draft.assigned_to} onChange={e=>setDraft({...draft,assigned_to:e.target.value})}><option value="">All</option><option value="me">Assigned to me</option><option value="unassigned">Unassigned</option></select></Filter><Filter label="Created from"><input className="field mt-2" type="date" value={draft.created_from} onChange={e=>setDraft({...draft,created_from:e.target.value})}/></Filter><Filter label="Created to"><input className="field mt-2" type="date" value={draft.created_to} onChange={e=>setDraft({...draft,created_to:e.target.value})}/></Filter><Button type="submit"><Search className="h-4 w-4"/>Apply</Button></form></Card>
    {error?<Alert title="Could not load registration requests" message={error}><Button type="button" variant="secondary" className="mt-4" onClick={()=>void load()}>Retry</Button></Alert>:null}
    {loading?<div className="space-y-3" aria-label="Loading registration requests">{[0,1,2,3].map(item=><Skeleton key={item} className="h-24 w-full"/>)}</div>:null}
    {empty?<Card className="py-12 text-center"><ClipboardList className="mx-auto h-8 w-8 text-muted"/><CardTitle className="mt-3">{result&&Object.values(result.counts).some(Boolean)?"No matching requests":"No registration requests yet"}</CardTitle><CardDescription>{result&&Object.values(result.counts).some(Boolean)?"Change the filters and search again.":"Durably received salon requests will appear here."}</CardDescription></Card>:null}
    {!loading&&!error&&result?.requests.length?<><div className="hidden overflow-hidden rounded-lg border border-line bg-white shadow-soft md:block"><div className="grid grid-cols-[150px_minmax(0,1.4fr)_minmax(0,1fr)_140px_150px] gap-4 border-b border-line bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-muted"><span>Reference</span><span>Salon & contact</span><span>Location</span><span>Status</span><span>Created</span></div>{result.requests.map(item=><Link key={item.id} href={`/platform/registration-requests/${item.id}`} className="grid grid-cols-[150px_minmax(0,1.4fr)_minmax(0,1fr)_140px_150px] gap-4 border-b border-line px-5 py-4 last:border-0 hover:bg-slate-50"><div className="font-mono text-xs font-semibold text-brand">{item.public_reference}</div><div className="min-w-0"><div className="flex items-center gap-2"><span className="truncate font-semibold text-ink">{item.salon_name||"Redacted request"}</span>{item.possible_duplicate?<span title="Possible duplicate"><AlertTriangle className="h-4 w-4 text-amber-600"/></span>:null}</div><div className="mt-1 truncate text-xs text-muted">{registrationQueueContactLine(item)}</div></div><div className="text-sm text-slate-700">{[item.city,item.state].filter(Boolean).join(", ")||"Redacted"}<div className="mt-1 text-xs text-muted">{item.assigned_to_name||"Unassigned"}</div></div><div><Badge value={item.status}/>{item.marketing_plan_interest?<div className="mt-2 text-xs text-muted">{item.marketing_plan_interest}</div>:null}</div><time className="text-sm text-slate-700" dateTime={item.created_at}>{formatDate(item.created_at)}</time></Link>)}</div>
    <div className="grid gap-3 md:hidden">{result.requests.map(item=><Link key={item.id} href={`/platform/registration-requests/${item.id}`} className="rounded-lg border border-line bg-white p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-xs font-semibold text-brand">{item.public_reference}</div><div className="mt-1 font-semibold text-ink">{item.salon_name||"Redacted request"}</div></div><Badge value={item.status}/></div><div className="mt-3 text-sm text-muted">{item.contact_full_name} · {item.contact_phone_masked}</div><div className="mt-2 text-xs text-muted">{[item.city,item.state].filter(Boolean).join(", ")} · {formatDate(item.created_at)}</div>{item.possible_duplicate?<div className="mt-3 flex items-center gap-2 text-xs font-semibold text-amber-700"><AlertTriangle className="h-4 w-4"/>Possible duplicate</div>:null}</Link>)}</div>
    <div className="flex items-center justify-between"><span className="text-sm text-muted">Showing {offset+1}–{offset+result.requests.length}</span><div className="flex gap-2"><Button type="button" variant="secondary" disabled={offset===0||loading} onClick={()=>void load(Math.max(0,offset-limit))}><ChevronLeft className="h-4 w-4"/>Previous</Button><Button type="button" variant="secondary" disabled={!result.has_more||loading} onClick={()=>void load(offset+limit)}>Next<ChevronRight className="h-4 w-4"/></Button></div></div></>:null}
  </div>
}
function Filter({label,children}:{label:string;children:React.ReactNode}){return <label><span className="text-sm font-semibold">{label}</span>{children}</label>}
function formatDate(value:string){return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
