import { apiRequest, apiRequestWithResponse } from "@/lib/api/client";
import { newBusinessActionKey, type DataClassification } from "@/lib/api/business";
export type { CapabilityDefinition } from "@/lib/api/access-contract";
import { accessDirectoryPath, type AccessDirectoryScope, type CapabilityDefinition } from "@/lib/api/access-contract";

export type AccessUser={id:string;email:string;full_name:string;status:string;principal_scope:AccessDirectoryScope;data_classification:DataClassification};
export type PlatformRoleAssignment={id:string;user_id:string;role:"platform_admin"|"platform_ops";status:"active"|"revoked";version:number;created_at:string;updated_at:string;user:AccessUser};
export type TenantMembership={id:string;salon_id:string;user_id:string;role:"tenant_owner"|"tenant_business_manager";status:"active"|"revoked";is_owner:boolean;version:number;created_at:string;updated_at:string;user:AccessUser};
export type SalonAssignment={id:string;salon_id:string;user_id:string;status:"active"|"revoked";permissions:string[];version:number;created_at:string;updated_at:string;user:AccessUser};
export type PIIGrant={id:string;salon_id:string;user_id:string;scope:"customers"|"calls"|"appointments"|"notifications";reason:string;expires_at:string;revoked_at?:string;version:number;created_by_user_id:string;created_at:string;updated_at:string;user:AccessUser};
export type AccessEvent={id:string;actor_user_id?:string;salon_id?:string;target_user_id?:string;event_type:string;object_type:string;object_id:string;details:Record<string,unknown>;created_at:string};
export type SupportAccessRequest={id:string;salon_id:string;platform_user_id:string;requested_by_user_id:string;status:"pending_owner_review"|"approved"|"rejected"|"cancelled"|"revoked";effective_status:"pending_owner_review"|"approved"|"rejected"|"cancelled"|"revoked"|"expired";reason:string;capabilities:string[];pii_scopes:Array<"calls">;requested_expires_at:string;approved_expires_at?:string;decision_by_user_id?:string;decision_at?:string;revoked_by_user_id?:string;revoked_at?:string;version:number;created_at:string;updated_at:string;user:AccessUser};
export type EffectiveSupportAccess={capabilities:string[];pii_scopes:string[];expires_at?:string};
export type TenantAccessWorkspace={memberships:TenantMembership[];platform_roles:PlatformRoleAssignment[];operator_assignments:SalonAssignment[];pii_grants:PIIGrant[];capabilities:CapabilityDefinition[];temporary_authorizations:SupportAccessRequest[]};
type NormalizedAccessResponse<T>={data:T;meta:{replayed:boolean;resource_version:number}};

export function listPlatformAccessUsers(query=""){return apiRequest<{users:AccessUser[]}>(accessDirectoryPath("platform",query))}
export function listTenantAccessUsers(salonID:string,query=""){return apiRequest<{users:AccessUser[]}>(accessDirectoryPath("tenant",query,salonID))}
export function listPlatformRoles(){return apiRequest<{assignments:PlatformRoleAssignment[]}>("/api/platform/access/roles")}
export function createPlatformUser(email:string,fullName:string,password:string,role:PlatformRoleAssignment["role"],status:PlatformRoleAssignment["status"],actionKey=newBusinessActionKey("platform-user-create")){return mutate<PlatformRoleAssignment>("/api/platform/access/platform-users","POST",{action_key:actionKey,email,full_name:fullName,password,role,status})}
export function updatePlatformUser(userID:string,email:string,fullName:string,password:string,role:PlatformRoleAssignment["role"],status:PlatformRoleAssignment["status"],expectedVersion:number,actionKey=newBusinessActionKey("platform-user-update")){return mutate<PlatformRoleAssignment>(`/api/platform/access/platform-users/${userID}`,"PUT",{action_key:actionKey,email,full_name:fullName,...(password?{password}:{}),role,status,expected_version:expectedVersion})}
export function listAccessCapabilities(){return apiRequest<{capabilities:CapabilityDefinition[]}>("/api/platform/access/capabilities")}
export function listMemberships(salonID:string){return apiRequest<{memberships:TenantMembership[]}>(`/api/platform/access/salons/${salonID}/memberships`)}
export function listSalonAssignments(salonID:string){return apiRequest<{assignments:SalonAssignment[]}>(`/api/platform/access/salons/${salonID}/assignments`)}
export function listPIIGrants(salonID:string){return apiRequest<{grants:PIIGrant[]}>(`/api/platform/access/salons/${salonID}/pii-grants`)}
export function listAccessAudit(salonID:string,limit=50,offset=0){return apiRequest<{events:AccessEvent[];limit:number;offset:number;has_more:boolean}>(`/api/platform/access/audit?salon_id=${encodeURIComponent(salonID)}&limit=${limit}&offset=${offset}`)}
export function listSupportAccessRequests(salonID:string){return apiRequest<{requests:SupportAccessRequest[]}>(`/api/platform/access/salons/${salonID}/support-requests`)}
export async function getTenantAccessWorkspace(salonID:string){return (await apiRequest<NormalizedAccessResponse<TenantAccessWorkspace>>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access`)).data}
export async function getEffectiveSupportAccess(salonID:string){return (await apiRequest<NormalizedAccessResponse<EffectiveSupportAccess>>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/effective`)).data}

async function mutate<T>(path:string,method:"PUT"|"POST",body:Record<string,unknown>){if(path.startsWith("/api/v2/platform/")){const{data,response}=await apiRequestWithResponse<NormalizedAccessResponse<T>>(path,{method,body:JSON.stringify(body)});return{data:data.data,replayed:data.meta.replayed||response.headers.get("X-Idempotent-Replay")==="true"}}const{data,response}=await apiRequestWithResponse<T>(path,{method,body:JSON.stringify(body)});return{data,replayed:response.headers.get("X-Idempotent-Replay")==="true"}}
export function mutatePlatformRole(userID:string,role:string,status:string,expectedVersion:number,actionKey=newBusinessActionKey("platform-role")){return mutate<PlatformRoleAssignment>(`/api/platform/access/platform-users/${userID}/role`,"PUT",{action_key:actionKey,role,status,expected_version:expectedVersion})}
export function mutateMembership(salonID:string,userID:string,role:string,status:string,expectedVersion:number,actionKey=newBusinessActionKey("tenant-membership")){return mutate<TenantMembership>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/team/${encodeURIComponent(userID)}`,"PUT",{action_key:actionKey,role,status,expected_version:expectedVersion})}
export function mutateSalonAssignment(salonID:string,userID:string,status:string,permissions:string[],expectedVersion:number,actionKey=newBusinessActionKey("salon-assignment")){return mutate<SalonAssignment>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/operators/${encodeURIComponent(userID)}`,"PUT",{action_key:actionKey,status,permissions,expected_version:expectedVersion})}
export function grantPII(salonID:string,userID:string,scope:string,reason:string,expiresAt:string,actionKey=newBusinessActionKey("pii-grant")){return mutate<PIIGrant>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/operators/pii-grants`,"POST",{action_key:actionKey,user_id:userID,scope,reason,expires_at:expiresAt})}
export function revokePII(salonID:string,grantID:string,expectedVersion:number,actionKey=newBusinessActionKey("pii-revoke")){return mutate<PIIGrant>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/operators/pii-grants/${encodeURIComponent(grantID)}/revoke`,"POST",{action_key:actionKey,expected_version:expectedVersion})}
export function createSupportAccessRequest(salonID:string,userID:string,capabilities:string[],piiScopes:string[],reason:string,expiresAt:string,actionKey=newBusinessActionKey("support-request")){return mutate<SupportAccessRequest>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/operators/temporary-authorizations`,"POST",{action_key:actionKey,user_id:userID,capabilities,pii_scopes:piiScopes,reason,expires_at:expiresAt})}
export function cancelSupportAccessRequest(salonID:string,requestID:string,expectedVersion:number,actionKey=newBusinessActionKey("support-cancel")){return mutate<SupportAccessRequest>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/operators/temporary-authorizations/${encodeURIComponent(requestID)}/cancel`,"POST",{action_key:actionKey,expected_version:expectedVersion})}
export function revokeSupportAccessRequest(salonID:string,requestID:string,expectedVersion:number,actionKey=newBusinessActionKey("support-revoke")){return mutate<SupportAccessRequest>(`/api/v2/platform/tenants/${encodeURIComponent(salonID)}/access/operators/temporary-authorizations/${encodeURIComponent(requestID)}/revoke`,"POST",{action_key:actionKey,expected_version:expectedVersion})}
